/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Panel;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
/**
 *
 * @author ASUS
 */
public class DataProduk1 extends javax.swing.JFrame { 
public Connection con;
    public Statement st;
    public ResultSet rs;
    public DefaultTableModel model;
    public int id =-1;
    
    /**
     * Creates new form DataProduk1
     */
    public DataProduk1() {
        initComponents();
        String[] header = {"id_barang", "nama_barang", "merek", "stok", "harga"};
        model = new DefaultTableModel(header, 0);
        tabelproduk1.setModel(model);   
        pp();
    }
    
    public void pp (){
        model.setRowCount(0);

        try {
            con = koneksi.konek();
            String sql = "SELECT * FROM produk";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                Object[] row = {
                    rs.getInt("id_barang"),   // Asumsi id ada di kolom pertama
                    rs.getString("nama_barang"),
                    rs.getString("merek"),
                    rs.getString("stok"),
                    rs.getString("harga"),
                };
                model.addRow(row);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error loading data: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextpecnarian = new javax.swing.JTextField();
        jBCari = new javax.swing.JButton();
        id_barang = new javax.swing.JLabel();
        harga = new javax.swing.JLabel();
        stok = new javax.swing.JLabel();
        jTextbarang = new javax.swing.JTextField();
        jTextStok = new javax.swing.JTextField();
        jTextHarga = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelproduk1 = new javax.swing.JTable();
        jBTambah = new javax.swing.JButton();
        jBSimpan = new javax.swing.JButton();
        Nmaproduk1 = new javax.swing.JLabel();
        jBEdit = new javax.swing.JButton();
        jBHapus = new javax.swing.JButton();
        jTextNmerek = new javax.swing.JTextField();
        jTextId = new javax.swing.JTextField();
        jId = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(599, 474));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/img/Back.png"))); // NOI18N

        jBCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/img/Search_3.png"))); // NOI18N

        id_barang.setText("Nama Barang");

        harga.setText("Harga");

        stok.setText("Stok");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("DATA PRODUK");

        tabelproduk1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tabelproduk1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelproduk1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelproduk1);

        jBTambah.setText("TAMBAH");
        jBTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBTambahMouseClicked(evt);
            }
        });

        jBSimpan.setText("SIMPAN");
        jBSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBSimpanMouseClicked(evt);
            }
        });
        jBSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSimpanActionPerformed(evt);
            }
        });

        Nmaproduk1.setText("Merek");

        jBEdit.setText("EDIT");
        jBEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditActionPerformed(evt);
            }
        });

        jBHapus.setText("HAPUS");

        jId.setText("Id_barang");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextbarang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(jTextHarga, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextStok, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextNmerek, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextId, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(78, 78, 78)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextpecnarian, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBCari))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jBTambah)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBSimpan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBEdit)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBHapus))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Nmaproduk1)
                                            .addComponent(id_barang)
                                            .addComponent(stok)
                                            .addComponent(harga)
                                            .addComponent(jId)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextpecnarian, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jBCari)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextbarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_barang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNmerek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nmaproduk1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stok))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(harga))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBTambah)
                    .addComponent(jBSimpan)
                    .addComponent(jBEdit)
                    .addComponent(jBHapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBTambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBTambahMouseClicked
             try {
    String sql = "INSERT INTO user (id_barang, nama_barang, merek, stok, harga) VALUES (?, ?, ?, ?, ?)";
    Connection con = koneksi.konek();
    PreparedStatement pst = con.prepareStatement(sql);
    
    pst.setString(1, jTextId.getText());  
    pst.setString(2, jTextbarang.getText()); 
    pst.setString(3, jTextNmerek.getText()); 
    pst.setString(4, jTextStok.getText());  
    pst.setString(5, jTextHarga.getText()); 
   
    
     
 
    JOptionPane.showMessageDialog(null, "Berhasil Menyimpan");
    int rowsAffected = pst.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "User saved successfully!");

                // Clear the input fields
                jTextId.setText("");
                jTextbarang.setText("");
                jTextNmerek.setText("");
                jTextStok.setText("");
                jTextHarga.setText("");
                

                // Reload the table data to show the new user
                pp();
            }
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Gagal Menyimpan: " + e.getMessage());
}

    }//GEN-LAST:event_jBTambahMouseClicked

    private void jBSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBSimpanMouseClicked
        
        try{
           String sql = "SELECT  * FROM produk WHERE id_barang='" + jTextId.getText() + "'";
           Connection con = koneksi.konek();
           PreparedStatement pst = con.prepareStatement(sql);
           pst.execute();
        }catch (Exception e){     
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jBSimpanMouseClicked

    private void tabelproduk1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelproduk1MouseClicked
       
        int row = tabelproduk1.getSelectedRow();
        
        if (row >= 0) {
                    // Ambil data dari baris yang diklik
                    id = Integer.parseInt(model.getValueAt(row, 0).toString()); // Ambil id (asumsi kolom 0 adalah id)
                   jTextbarang.setText(model.getValueAt(row, 1).toString());
                   jTextNmerek.setText(model.getValueAt(row, 2).toString());
                     jTextStok.setText(model.getValueAt(row, 3).toString());
                  jTextHarga.setText(model.getValueAt(row, 4).toString());
                }
    }//GEN-LAST:event_tabelproduk1MouseClicked

    private void jBEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditActionPerformed
       
        try {
        // Query untuk update data
        String sql = "UPDATE produk SET nama_barang = ?, merek = ?, stok = ?, harga = ? WHERE id_barang = ?";
        con = koneksi.konek();
       PreparedStatement pst = con.prepareStatement(sql);
    

        // Set nilai yang baru dari input user
        pst.setString(1, jTextbarang.getText());
        pst.setString(2, jTextNmerek.getText());
        pst.setString(3,  jTextStok.getText());
        pst.setString(4,  jTextHarga.getText());
        pst.setInt(5, id); // Update berdasarkan id

        // Eksekusi update
        int rowsAffected = pst.executeUpdate();

        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(null, "Data berhasil di-update!");

            // Reload tabel setelah update
            pp();

            // Kosongkan field input dan reset selectedUserId
            id = -1;
            jTextbarang.setText("");
            jTextNmerek.setText("");
            jTextStok.setText("");
           jTextHarga.setText("");
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Gagal mengupdate data: " + e.getMessage());
    } 
    }//GEN-LAST:event_jBEditActionPerformed

    private void jBSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSimpanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBSimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataProduk1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataProduk1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataProduk1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataProduk1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataProduk1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nmaproduk1;
    private javax.swing.JLabel harga;
    private javax.swing.JLabel id_barang;
    private javax.swing.JButton jBCari;
    private javax.swing.JButton jBEdit;
    private javax.swing.JButton jBHapus;
    private javax.swing.JButton jBSimpan;
    private javax.swing.JButton jBTambah;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jId;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextHarga;
    private javax.swing.JTextField jTextId;
    private javax.swing.JTextField jTextNmerek;
    private javax.swing.JTextField jTextStok;
    private javax.swing.JTextField jTextbarang;
    private javax.swing.JTextField jTextpecnarian;
    private javax.swing.JLabel stok;
    private javax.swing.JTable tabelproduk1;
    // End of variables declaration//GEN-END:variables

}
